apiVersion: v1
kind: Pod
metadata:
  name: irnnaLabelsAndSelectorPod
  labels:
    app: App01
    function: frontend
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080